spring:
  h2:
    console:
      enabled: true
      path: /h2-console     # (1) Context path ??
  datasource:
    url: jdbc:h2:mem:test     # (2) JDBC URL ??
  jpa:
    hibernate:
      ddl-auto: create  # (1) ??? ?? ??
    show-sql: true      # (2) SQL ?? ??
logging:         # (1) ?? ?? ??
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG
mail:
  address:
    admin: admin@gmail.com
jwt:
  key: codestates123412341234123412341234         # ??? ??? ??? ?? ???? ????.
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 420

  # ${JWT_SECRET_KEY}